In [32]:
import numpy as np
x=np.array([1,2,3,4,5])
N= 
matrix = np.column_stack([x**(N-i-1) for i in range(N)]) 
print(matrix)



[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [33]:
#Similar matrix is created using np.vander function in numpy

import numpy as np
x=np.array([1,2,3,4,5])
N=len(x)
matrix1 = np.vander(x,N,increasing=False)
print(matrix1) 


[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


# 2. Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [41]:
arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = len(arr)
k = 3
l=[]
for i in range(0,N-k+1):
    y1 = round(sum(arr[i:i+k])/k,2)
    l.append(y1)
print(l)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
